import './globals.css'
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
import dynamic from 'next/dynamic'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const Navbar = dynamic(
  ()=>import('./components/Navbar').then((ctx)=>ctx.default),
  {
    ssr:false,
  }
);
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
   
    <html lang="en">   
     <Navbar/>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
